### ISSUE TITLE
Add Italian translation

### ISSUE THREAD

**Issue by santisoler** [santisoler/cc-licenses#13]
After @Magicianred comment on #12 would be great to have an Italian translation of the `README.md` and for the license texts.

The changes that would be needed are:

- [ ] Add a new `it` folder containing a `README.md` file which should be a translation from the English `README.md`.
- [ ] Add the Italian version of the license texts. 
- [ ] Add a badge on the main `README.md` pointing to the Italian translation folder.
- [ ] Add a badge on `it/README.md` pointing to the main `README.md` (see the other translations).

You don't need to translate the licenses texts, they can be downloaded from Creative Commons website. The last time I checked, only the English version of the license texts could be downloaded as a `.txt` file, so we used to have to reformat the HTML files as `.txt` files. After https://github.com/creativecommons/cc-licenses/pull/56 has been merged, we should be able to download the `txt` files from CC, but I don't know if that code has been deployed yet. I'll ask and comment here if I hear some news.

**Comment by Magicianred** [comment]
Great :)
