### ISSUE TITLE
Possibility of adding KiCad footpronts/logotypes to this Git

### ISSUE THREAD

**Issue by TweetyDaBird** [santisoler/cc-licenses#18]
I'm not sure if this is wanted or the right place for it but I'd thought I'd ask. It doesn't really seem to fit into any other place, and it might help someone. If nothing else it should drive more traffic your way perhaps.

I have been using the resources here to add license information to my own OpenHardware projects published on GitHub simply because it is convenient once I know what license I want, vs having to muddle through the 'chooser' on CC's webpage. One of the things I created for myself was the KiCad libraries to add the logo for the license on the PCB itself. Ie, basically taking the images provided and scaling/cleaning them up to make a reasonable logo to add to the silkscreen. 

With minimal cleanup, I'd say they could be added to this Git, usable for any other OpenHardware enthusiast in their projects. And as part of a package, IMHO it would fit here.

Let me know if you feel it appropriate, and I'll make a pull request.

**Comment by santisoler** [comment]
Hi @TweetyDaBird! Thanks for opening this PR!

> I have been using the resources here to add license information to my own OpenHardware projects published on GitHub simply because it is convenient once I know what license I want, vs having to muddle through the 'chooser' on CC's webpage.

I'm really glad that you found this repo helpful! I started it as a personal resource for applying CC licenses to some of my repos, but apparently a lot of people had the same need.

Regarding your proposal. If I understood well, you took the CC logos and converted them into a KiCad file, so it can be easily imported and finally printed into a PCB, right?

I would say that such kind of files are slightly out of the scope of this repo: my main idea for it was to provide an easy way to add a CC license into GitHub repos, but without creating any derivatives from their logos or license notices (the plain text license files are taken from their website, and the logos are just added into the READMEs as links).
Therefore I would say that this repo is not the best place for your CC logos in KiCad format.

Nevertheless, if I were you, I would try to approach the people at Creative Commons: they might be interesting in your work!
I'm sure you're not the only one interested in putting CC licenses into your OpenHardware projects. Perhaps they could offer your files within their https://creativecommons.org/about/downloads/ section.

Meanwhile, you could create your own repo to host them. I would gladly add links to it in the `README.md` as a related project.

Thanks again for the shout out, I really appreciate your initiative and I'm particularly amazed by OpenHardware enthusiast!

**Comment by TweetyDaBird** [comment]
> Regarding your proposal. If I understood well, you took the CC logos and converted them into a KiCad file, so it can be easily imported and finally printed into a PCB, right?

Yes, that's correct.

> Nevertheless, if I were you, I would try to approach the people at Creative Commons: they might be interesting in your work! I'm sure you're not the only one interested in putting CC licenses into your OpenHardware projects. Perhaps they could offer your files within their https://creativecommons.org/about/downloads/ section.

That's a really good idea, I'll try that.
 
> Meanwhile, you could create your own repo to host them. I would gladly add links to it in the `README.md` as a related project.

Again, a very good idea, I'll hash something out tomorrow, and reply back with the links etc.
 
> Thanks again for the shout out, I really appreciate your initiative and I'm particularly amazed by OpenHardware enthusiast!

No problem, like said, I have had great use of the texts you posted.

**Comment by santisoler** [comment]
> Again, a very good idea, I'll hash something out tomorrow, and reply back with the links etc.

Great! Feel free to ping me when you have them. I'm closing this issue now, but you can continue comment here.
