### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by santisoler** [santisoler/cc-licenses#3]
After #2 opened by @cyb3rko, I think would be nice to add a Spanish translation of the CC Licenses and the `README.md`.
We can wait until #2 is merged, but my idea so far is having one directory for each translation. Like:

```
de
 ├── LICENSE-CC-BY
 ├── LICENSE-CC-BY-SA
 └── README.md 
es
 ├── LICENSE-CC-BY
 ├── LICENSE-CC-BY-SA
 └── README.md 
LICENSE-CC-BY
LICENSE-CC-BY-SA
README.md 
```

We should check if GitHub automatically recognizes the license out of a translated `LICENSE` file. If not, we should add a note encouraging people to add both the English and the translated version of the license text.

**Comment by cyb3rko** [comment]
As discussed in #2 only the original license is recognized by GitHub.

And where do you need the help?
There are translations on the original creative commons website (that I also used), I could include the translations.

**Comment by santisoler** [comment]
I'm thinking to add a notice to add the English LICENSE file if the author wants GitHub to recognize the license. I'll add it to the main `README.md` and to the future `es/README.md`. I'll need your help to also add it to the `de/README.md`, if that's ok for you.

**Comment by cyb3rko** [comment]
I'm ok with that. Just add it, I will then translate it.

**Comment by frxncismor** [comment]
I can help with the spanish translation

**Comment by cyb3rko** [comment]
The licences are already officially translated, they just have to get included.

**Comment by santisoler** [comment]
Hi @frxncismor! Sure, feel free to fork, create a new branch and open a PR.
As @cyb3rko mentioned, we would only need to translate the `README.md` and just copy the licenses texts from Creative Commons website. As I pointed out on the Issue description, all files would live inside the `es` directory. Although you might also need to add the badge to the Spanish translation to the main `README.md`. If you need any help, please don't hesitate to ask.

**Comment by frxncismor** [comment]
@santisoler Do you want the document redacted formal ("usted") or informal ("tu/vos")?

**Comment by cyb3rko** [comment]
@frxncismor They are already completed:

https://creativecommons.org/licenses/by/4.0/legalcode.es
https://creativecommons.org/licenses/by-sa/4.0/legalcode.es

I'm currently working on converting them to unformatted text. The first license I've already finished, the second one is on the way.
Maybe you start with translating the README, that would be for sure more productive than working on the same licence text.

**Comment by frxncismor** [comment]
@cyb3rko Thanks man, i'm already working on the README.

**Comment by santisoler** [comment]
> @santisoler Do you want the document redacted formal ("usted") or informal ("tu/vos")?

I would like to keep it informal. I think the license text covers the formal part of the process, so we may want to keep the instructions on the `README.md` as friendly as we can.
